config/routes.rb
OmrPinterest::Application.routes.draw do
  resources :vins do
    member do
      put "like", to: "vins#upvote"
      put "dislike", to: "vins#downvote"
    end
  end

  devise_for :users
  root "vins#index"
  get "about" => "pages#about"

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :vins, dependent: :destroy

  validates :name, presence: true

end

app/models/vin.rb
class Vin < ActiveRecord::Base
	acts_as_votable
	belongs_to :user

	has_attached_file :image, 
	:styles => { :medium => "300x300>", :thumb => "100x100>" }
	
	validates :image, presence: true
	validates :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/vins_controller.rb
class VinsController < ApplicationController
  before_action :set_vin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  respond_to :html

  def index
    @vins = Vin.all.order(created_at: :desc).paginate(page: params[:page], per_page: 15)
    respond_with(@vins)
  end

  def show
  end

  def new
    @vin = current_user.vins.build
    respond_with(@vin)
  end

  def edit
  end

  def create
    @vin = current_user.vins.build(vin_params)
    if @vin.save
      redirect_to @vin, notice: "Vin successfully created"
    else
      render action: 'new'
    end
  end

  def update
    @vin.update(vin_params)
    respond_with(@vin)
  end

  def destroy
    @vin.destroy
    redirect_to root_url, notice: "Vin successfully destroyed"
    respond_with(@vin)
  end

  def upvote
    @vin = Vin.find(params[:id])
    @vin.upvote_by current_user
    redirect_to root_url
  end

  def downvote
    @vin = Vin.find(params[:id])
    @vin.downvote_from current_user
    redirect_to root_url
  end


  private
    def set_vin
      @vin = Vin.find(params[:id])
    end

    def correct_user
      @vin = current_user.vins.find_by(id: params[:id])
      redirect_to vins_path, 
      notice: "This area is restricted to the owner" if @vin.nil?
    end

    def vin_params
      params.require(:vin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/vins_helper.rb
module VinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Vinteresting", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to root_path do %>
          <span class="glyphicon glyphicon-home"></span> Home
          <% end %>
        </li>
        <li><%= link_to about_path do %>
          <span class="glyphicon glyphicon-info-sign"></span> About
          <% end %>
        </li>
        <% if user_signed_in? %>
        <li><%= link_to new_vin_path do %>
          <span class="glyphicon glyphicon-plus"></span> New Vin
        <% end %>
        </li>
        <li><%= link_to edit_user_registration_path do %>
          <span class="glyphicon glyphicon-pencil"></span> Account Settings
          <% end %>
        </li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
          <span class="glyphicon glyphicon-off"></span> Log Out
          <% end %>
        </li>
        <% else %>
        <li><%= link_to new_user_session_path do %>
          <span class="glyphicon glyphicon-ok-sign"></span> Log In
          <% end %>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vinteresting</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width", initial-scale="1.0">
</head>
<body>
	<%= render 'layouts/header' %>
	<div class = "container">
		<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>

		<% end %>
<%= yield %>
	</div>
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center h-color">
	<h1>Welcome to Vinterest!</h1>
	
	<p><%= link_to "Login", new_user_session_path, class: "btn-warning btn-lg round" %>
	<%= link_to "Register", new_user_registration_path, class: "btn-primary btn-lg round" %>
	</p>
</div>

app/views/pages/about.html.erb
<section>
	<div class= "about-profile center round">
		<%= image_tag("picture.JPG", width: 180, height: 180, :alt => "Picture", :class => "about-image super-round") %>
		<h3>Heya, I'm Luke and this is one of many projects on my road to learn Rails</h3>
		<p>This project is somewhat an attempt to copy Pinterest. I used various gems such as devise for creating users, imagemagick for uploading picture, AWS3 for storing images on external source along with many others gems that were a great help along the way. Whole development process was on a Windows OS so it was a "Rocky Road" but i managed to complete it after many hardships. If You are interesting in following me on my journey to learn Rails, check out my twitter <a href="https://twitter.com/Velsu">@Velsu</a> or my <a href="http://github.com/Velsu">github</a> account.</p>
			<div class="icons center round">
				<%= link_to href: 'https://twitter.com/Velsu' do %>
    				<%= image_tag 'twitter-white.png', width: 50, height: 50, alt: 'twitter icon', class: "icon super-round" %>
				<% end %>
				<%= link_to href: 'https://github.com/Velsu' do %>
    				<%= image_tag 'github-white.png', width: 50, height: 50, alt: 'github icon', class: "icon super-round" %>
				<% end %>
					<%= link_to href: 'https://www.facebook.com/profile.php?id=100000761255888' do %>
    			<%= image_tag 'facebook-white.png', width: 50, height: 50, alt: 'facebook icon', class: "icon super-round" %>
				<% end %>
			</div>
	</div>
</section>


app/views/pages/home.html.erb
<div class="jumbotron center h-color">
	<h1>Welcome to Vinterest!</h1>
	
<% unless user_signed_in? %>
	<p><%= link_to "Login", new_user_session_path, class: "btn-warning btn-lg round" %>
	<%= link_to "Register", new_user_registration_path, class: "btn-primary btn-lg round" %>
	</p>
	<% end %>
</div>

app/views/vins/_form.html.erb
<%= form_for @vin, html: { multipart: true } do |f| %>
  <% if @vin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vin.errors.count, "error") %> prohibited this vin from being saved:</h2>

      <ul>
      <% @vin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/vins/edit.html.erb
<h1>Editing vin</h1>

<%= render 'form' %>

<%= link_to 'Show', @vin %> |
<%= link_to 'Back', vins_path %>

app/views/vins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="vins" class="transitions-enabled">
  <% @vins.each do |vin| %>
  <div class="box panel panel-default">
      <%= link_to image_tag(vin.image.url(:medium)), vin %>
      <div class="panel-body">
        <p><%= vin.description %></p>
        <p><strong><%= vin.user.name if vin.user %></strong></p>
        
        <div class="btn-group">
      <%= link_to like_vin_path(vin), method: :put, class: "btn btn" do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
        Up
        <%= vin.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_vin_path(vin), method: :put, class: "btn btn" do %>
        <span class="glyphicon glyphicon-chevron-down">
        Down
        <%= vin.get_downvotes.size %>
      <% end %>
    </div>
        <% if current_user && (vin.user == current_user) %>
         <div class="actions">
          <%= link_to edit_vin_path(vin) do %>
          <span class="glyphicon glyphicon-edit"></span> Edit
          <% end %>
          <%= link_to vin, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-trash"></span> Delete
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

<div class="center">
<%= will_paginate @posts %>
</div>

app/views/vins/new.html.erb
<h1>New vin</h1>

<%= render 'form' %>

<%= link_to 'Back', vins_path %>

app/views/vins/show.html.erb
<%= link_to 'Home', vins_path %>

<div class="row"> 
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
				<%= image_tag @vin.image.url(:medium) %>
			</div>
			
				<p><%= @vin.description %></p>
				<p><strong><%= @vin.user.name if @vin.user %></strong></p>
				<div class="btn-group">
      <%= link_to like_vin_path(@vin), method: :put, class: "btn btn-xs" do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
        Upvote
        <%= @vin.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_vin_path(@vin), method: :put, class: "btn btn-xs" do %>
        <span class="glyphicon glyphicon-chevron-down">
        Downvote
        <%= @vin.get_downvotes.size %>
      <% end %>
    </div>

				<% if @vin.user == current_user %>
				<%= link_to edit_vin_path(@vin) do %>
				<span class="glyphicon glyphicon-edit"></span> Edit
				<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>